# Generated by Django 5.1 on 2024-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='check_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=12)),
                ('tags', models.CharField(max_length=12)),
                ('score', models.PositiveIntegerField()),
                ('map', models.ImageField(upload_to='map_pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='flow_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=12)),
                ('tags', models.CharField(max_length=12)),
                ('score', models.PositiveIntegerField()),
                ('answers', models.ManyToManyField(related_name='flowcharts', to='Listening.answers')),
                ('steps', models.ManyToManyField(related_name='flowcharts', to='Listening.steps')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
